#!/bin/sh
# chkconfig: - 60 40
# description: GrowthForecast
export HOME=/home/growthforecast
source $HOME/perl5/perlbrew/etc/bashrc
perlbrew use perl-5.16.2
USER="root"
 
PID_FILE=/var/run/growthforecast/growthforecast.pid
LOG_FILE=/var/log/growthforecast/growthforecast.log
PSNAME="growthforecast.pl"
 
start() {
  PID=`pgrep -fo "$PSNAME"`
  if [ -z "$PID" ]; then
    if [ -f $PID_FILE ]; then rm -f $PID_FILE; fi
  else
    echo "growthforecast already started."
  fi
  echo -n "Starting growthforecast: "
  perl $HOME/GrowthForecast/growthforecast.pl --port=5125 --host 0.0.0.0 --front-proxy 0.0.0.0 \
    >>$LOG_FILE 2>&1 & echo $! > $PID_FILE
  echo "done."
}
 
stop() {
  PID=`pgrep -f "$PSNAME"`
  if [ -z "$PID" ]; then
    echo "growthforecast already stopped."
    exit 0
  fi
  echo -n "Stopping growthforecast: "
  rm -f $PID_FILE
  pkill -TERM -f "$PSNAME"
  echo "done."
}

status() {
  PID=`pgrep -f "$PSNAME"`
  if [ -z "$PID" ]; then
    echo "growthforecast stopped."
  else
    echo "growthforecast already started."
  fi
}
 
usage() {
  echo "Usage: `basename $0`  {start|stop|restart}"
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        usage
        ;;
esac
